### ISSUE TITLE
Edge fails on CI

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/ckeditor4-react#12]
Edge 18 on CI fails:

```
✖ "after each" hook
      Edge 18.17763.0 (Windows 10 0.0.0)
      Edge 18.17763.0 (Windows 10 0.0.0)
    TypeError: Unable to get property 'call' of undefined or null reference
    ✖ "before each" hook for "is a function"
      Edge 18.17763.0 (Windows 10 0.0.0)
      Edge 18.17763.0 (Windows 10 0.0.0)
    TypeError: Unable to get property 'call' of undefined or null reference
```

```json
{
    "message": "Object expected\nat https://cdn.ckeditor.com/4.11.1/standard-all/ckeditor.js:1206:27\n\nTypeError: Object expected\n   at a (https://cdn.ckeditor.com/4.11.1/standard-all/ckeditor.js:1206:27)\n   at Anonymous function (https://cdn.ckeditor.com/4.11.1/standard-all/ckeditor.js:27:470)",
    "str": "Object expected\nat https://cdn.ckeditor.com/4.11.1/standard-all/ckeditor.js:1206:27\n\nTypeError: Object expected\n   at a (https://cdn.ckeditor.com/4.11.1/standard-all/ckeditor.js:1206:27)\n   at Anonymous function (https://cdn.ckeditor.com/4.11.1/standard-all/ckeditor.js:27:470)"
  }
```

**Comment by Comandeer** [comment]
Fixed in #13.
